version: '3.9'

services:
    cassandra:
        # restart: always
        hostname: my-cassandra
        image: cassandra:3.11.2
        ports:
            - "9042:9042"
        environment:
           CASSANDRA_RPC_ADDRESS: "0.0.0.0"
           CASSANDRA_START_RPC: "true"
           CASSANDRA_BROADCAST_ADDRESS: "127.0.0.1"
           CASSANDRA_LISTEN_ADDRESS: "127.0.0.1"
#         127.0.0.1 default
        volumes:
            - "logs/cassandra:/var/log/cassandra/"
        healthcheck:
            test: [ "CMD", "nodetool", "-u", "cassandra", "-pw", "cassandra",  "status" ]
            interval: 5s
            timeout: 10s
            retries: 60
