version: '3.3'

services:
    filesystem:
        restart: always
        build: .
        privileged: true
        command: dotnet CassandraFS/CassandraFS/bin/Debug/netcoreapp3.1/CassandraFS.dll mountPoint/
        ports:
            - 5000:80