version: '3.9'

services:
    filesystem:
#        restart: always
        build: .
        privileged: true
#        command: dotnet CassandraFS/CassandraFS/bin/Debug/netcoreapp3.1/CassandraFS.dll /app/containerMountPoint
        command: dotnet CassandraFS/CassandraFS/bin/Debug/net6.0/CassandraFS.dll /app/mountPoint
        ports:
            - "5000:80"
        volumes:
#            - type: volume
#              source: mountPoint
#              target: /mountPoint
            - "/home/CassandraFS/mountPoint:/app/containerMountPoint"
#    ftp:
#        image: kibatic/proftpd
#        network_mode: "host"
#        restart: unless-stopped
#        privileged: true
#        environment:
#           FTP_LIST: "user:pass"
#           USERADD_OPTIONS: "-o --gid 33 --uid 33"
#        volumes:
#            - ./mountPoint:/home/user
