version: '3.9'

services:
    cassandra:
#        restart: always
        image: cassandra
        ports:
            - "9042:9042"
        environment:
            CASSANDRA_BROADCAST_ADDRESS: "127.0.0.1"
            CASSANDRA_LISTEN_ADDRESS: "127.0.0.1"
#        volumes:
#            - "C:/FTP/Test/logs/cassandra:/var/log/cassandra/"
#        healthcheck:
#            test: [ "CMD", "nodetool", "-u", "cassandra", "-pw", "cassandra",  "status" ]
#            interval: 5s
#            timeout: 10s
#            retries: 60
    filesystem:
        depends_on:
            - cassandra
        build: .
        privileged: true
        ports:
          - "21:21"
          - "30000-30009:30000-30009"
        environment:
          FTP_LIST: "cassandra-fs:pass"
          TESTING: 1
#        volumes:
#          - "C:/FTP/Test/logs/FS:/app/CassandraFS/CassandraFS/bin/Debug/net6.0/logs"
#          - "C:/FTP/Test/logs/FS/testing:/app/CassandraFS/FileSystemTests/bin/Debug/net6.0/logs"
