version: '3.9'

services:
    cassandra:
        # restart: always
        hostname: my-cassandra
        image: cassandra
        ports:
            - 9042:9042
        environment:
           - CASSANDRA_RPC_ADDRESS=0.0.0.0
           - CASSANDRA_START_RPC=true
           - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1
           - CASSANDRA_LISTEN_ADDRESS=127.0.0.1
#         127.0.0.1 default
