version: '3.3'

services:
    cassandra:
        logging:
            driver: none
        restart: always
        hostname: my-cassandra
        image: cassandra
        ports:
            - 9042:9042
        environment:
         #  - CASSANDRA_RPC_ADDRESS=0.0.0.0
         #  - CASSANDRA_START_RPC=true
            - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1
            - CASSANDRA_LISTEN_ADDRESS=127.0.0.1
        # 127.0.0.1 default

    filesystem:
        restart: always
        depends_on:
            - cassandra
        build: .
        privileged: true
        command: dotnet CassandraFS/CassandraFS/bin/Debug/netcoreapp3.1/CassandraFS.dll /home/myusername
        ports:
            - 5000:80
    # proftpd:
    #    image: kibatic/proftpd
    #    network_mode: "host"
    #    restart: unless-stopped
    #    environment:
    #      FTP_LIST: "myusername:mypassword"
        #  USERADD_OPTIONS: "-o --gid 33 --uid 33"
     #   volumes:
     #     - "/the_direcotry_on_the_host:/home/jazzmutant/Work/CassandraFS/mountPoint/"
