FROM ubuntu:18.04
ARG DEBIAN_FRONTEND=noninteractive

FROM microsoft/aspnetcore:2.0 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2.0 AS build
WORKDIR /src
WORKDIR /app


#RUN apt-get update -qq && \
#	apt-get install -y proftpd && \
#	apt-get clean && \
#    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#RUN sed -i "s/# DefaultRoot/DefaultRoot/" /etc/proftpd/proftpd.conf

#EXPOSE 20 21

# ADD docker-entrypoint.sh /usr/local/sbin/docker-entrypoint.sh
# ENTRYPOINT ["/usr/local/sbin/docker-entrypoint.sh"]

#CMD ["proftpd", "--nodaemon"]



RUN apt-get update
RUN apt-get install apt-transport-https -y
RUN apt-get update
RUN apt install libtool -y
RUN apt-get install -y libtool-bin
RUN apt install wget -y
RUN wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN apt-get update

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN apt-get upgrade -y
RUN apt-get update --fix-missing
RUN apt-get install -y dotnet-sdk-3.1
RUN apt-get install -y fuse
RUN apt-get install -y libfuse-dev

RUN apt-get install libgtk2.0-dev -y
RUN apt-get install libglib2.0-dev -y

RUN apt-get -y install sudo
RUN useradd -m userftp && echo "userftp:pass" | chpasswd && adduser userftp sudo

#USER docker


ADD . .
RUN chmod +x build-libs.sh
RUN sh build-libs.sh

EXPOSE 20
EXPOSE 21


