version: '3.3'

services:
    cassandra:
        restart: always
        image: cassandra
        ports:
            - 9042:9042
        environment:
            - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1
            - CASSANDRA_LISTEN_ADDRESS=127.0.0.1
    filesystem:
        depends_on:
            - cassandra
        build: .
        privileged: true
        ports:
          - "21:21"
          - "30000-30009:30000-30009"
        environment:
          FTP_LIST: "cassandra-fs:pass"
          TESTING: 1
        restart: always
